# Generated by Django 4.1.3 on 2023-01-24 08:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentPollutant',
            fields=[
                ('recent_pollutant_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('pm25', models.FloatField()),
                ('_type', models.CharField(choices=[('real', 'real'), ('predicted', 'predicted')], max_length=9)),
            ],
            options={
                'db_table': 'recent_pollutants',
            },
        ),
    ]
