# Generated by Django 4.1.3 on 2023-01-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recentpollutant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentpollutant',
            name='_type',
            field=models.CharField(choices=[('real', 'real'), ('predicted', 'predicted')], db_column='type', max_length=9),
        ),
    ]
