# Generated by Django 4.1.3 on 2022-12-05 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.city')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('time_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'timestamps',
            },
        ),
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('pollutant_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('NO2', models.FloatField()),
                ('CO', models.FloatField()),
                ('O3', models.FloatField()),
                ('SO2', models.FloatField()),
                ('PM10', models.FloatField()),
                ('PM25', models.FloatField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.district')),
                ('timestamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.timestamp')),
            ],
            options={
                'db_table': 'pollutants',
            },
        ),
    ]
