# Generated by Django 4.1.3 on 2023-01-10 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollutant',
            old_name='CO',
            new_name='co',
        ),
        migrations.RenameField(
            model_name='pollutant',
            old_name='NO2',
            new_name='no2',
        ),
        migrations.RenameField(
            model_name='pollutant',
            old_name='O3',
            new_name='o3',
        ),
        migrations.RenameField(
            model_name='pollutant',
            old_name='PM10',
            new_name='pm10',
        ),
        migrations.RenameField(
            model_name='pollutant',
            old_name='PM25',
            new_name='pm25',
        ),
        migrations.RenameField(
            model_name='pollutant',
            old_name='SO2',
            new_name='so2',
        ),
    ]
